# Homework 2
Sam Friedman

## Problem 1
Find d-separated nodes. Assume that we have a Bayesian network graph $\mathit{G}$. Given a set of observed nodes $\mathbf{E}$, we want to find the set of nodes $\mathit{Y}$ that contains all nodes that are d-separated from the source node $X$.
    
    

In [10]:
import math
x = math.fsum([1,-0.7])
print(x)



0.30000000000000004


ImportError: No module named 'decimal.Decimal'; 'decimal' is not a package

In [16]:
import decimal
dec = decimal.Decimal
x = dec(1.0)-dec(0.7)
x = decimal.add(1-0.7)


AttributeError: module 'decimal' has no attribute 'add'

In [77]:
data_list = [
    [('C',1,0.1),('A',0),('B',0)], # [(variable, value, probability),(givenVar, givenVal),...,(givenVar, givenVal)]
    [('C',1,0.3),('A',1),('B',0)],
    [('C',1,0.5),('A',0),('B',1)],
    [('C',1,0.9),('A',1),('B',1)]
]

In [51]:
data=[('C',1,0.1),('A',1),('B',0)]# [(variable, value, probability),(givenVar, givenVal),...,(givenVar, givenVal)]

In [10]:
import numpy as np

In [83]:
def cpd_init(data):
    size_ary = [2]
    var_index = [data[0][0]]
    for given_var in data[1:]:
        #print(given_var)
        var_index.append(given_var[0]) # add var name to index
        size_ary.append(2)
    cpd = np.zeros(size_ary)
    return cpd
    
cpd = cpd_init(data)

print(cpd)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [84]:
def update_cpd(data, cpd):
    # add prob. to cpd based on data
    prob_idx = list(np.zeros([len(data)],dtype=int))
    for var in data:
        idx = var_index.index(var[0])
        prob_idx[idx] = var[1]
    prob_idx = tuple(prob_idx)
    print(prob_idx)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
for data in data

In [52]:
var_index

['C', 'B', 'A']

In [69]:
cpd = np.zeros(size_ary)
print(cpd)
# add prob. to cpd based on data
prob_idx = list(np.zeros([len(data)],dtype=int))
for var in data:
    idx = var_index.index(var[0])
    prob_idx[idx] = var[1]
prob_idx = tuple(prob_idx)
print(prob_idx)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
(1, 0, 1)


In [76]:
print(cpd[prob_idx])
val = data[0][2]
print(val)
cpd[prob_idx]=val
print(cpd)
alt_prob_index = list(prob_idx)
if data[0][1] == 0:
    alt_idx = 1
else:
    alt_idx = 0
alt_prob_index[0] = alt_idx
cpd[tuple(alt_prob_index)]=1-val
cpd



0.1
0.1
[[[0.  0.9]
  [0.  0. ]]

 [[0.  0.1]
  [0.  0. ]]]


array([[[0. , 0.9],
        [0. , 0. ]],

       [[0. , 0.1],
        [0. , 0. ]]])

In [104]:
ary = [1,1,0]
ary[0] ^= 1
ary

[0, 1, 0]

In [24]:
var_index = []
var_data = data[0]
var_index.append(var_data[0])
if len(data)>1:
    # make multidimensional array table
var_ary = []
var_value = var_data[1]
var_prob = var_data[2]
if var_value == 0:
    var_ary.append(var_prob)
    var_ary.append(1-var_prob)
else:
    var_ary.append(1-var_prob)
    var_ary.append(var_prob)
var_ary

[0.9, 0.1]

In [116]:
with open('project_cpds.txt', 'r') as f:
    for raw_line in f:
        line = raw_line.split()
#         print(raw_line)
        print(line)
        if '=' in line:
            # build data list
            data_list = []
            prob = line[-1]
            data_list.append((line[0][0],line[0][1],prob))
            for x in line[1:]:
                if x == '|':
                    continue
                if x == '=':
                    break
                if x[0].isalpha() and x[1].isdigit():
                    data_list.append((x[0],x[1]))
            print(data_list)

['A1', '=', '0.7']
[('A', '1', '0.7')]
['B1', '=', '0.4']
[('B', '1', '0.4')]
['C1', '|', 'A0,', 'B0', '=', '0.1']
[('C', '1', '0.1'), ('A', '0'), ('B', '0')]
['C1', '|', 'A1,', 'B0', '=', '0.3']
[('C', '1', '0.3'), ('A', '1'), ('B', '0')]
['D1', '|', 'C0', '=', '0.8']
[('D', '1', '0.8'), ('C', '0')]
['D1', '|', 'C1', '=', '0.3']
[('D', '1', '0.3'), ('C', '1')]
['F1', '|', 'D0', '=', '0.1']
[('F', '1', '0.1'), ('D', '0')]
['F1', '|', 'D1', '=', '0.7']
[('F', '1', '0.7'), ('D', '1')]
['B1', '=', '0.4']
[('B', '1', '0.4')]
['C1', '|', 'A0,', 'B1', '=', '0.5']
[('C', '1', '0.5'), ('A', '0'), ('B', '1')]
['C1', '|', 'A1,', 'B1', '=', '0.9']
[('C', '1', '0.9'), ('A', '1'), ('B', '1')]
['E1', '|', 'C0', '=', '0.2']
[('E', '1', '0.2'), ('C', '0')]
['E1', '|', 'C1', '=', '0.6']
[('E', '1', '0.6'), ('C', '1')]
['G1', '|', 'D0', '=', '0.9']
[('G', '1', '0.9'), ('D', '0')]
['G1', '|', 'D1', '=', '0.4']
[('G', '1', '0.4'), ('D', '1')]


In [1]:
from Friedman_Sam_hw2 import Graph, CPD, read_file

(G, queries) = read_file('project.txt')
G.edges

TypeError: unsupported operand type(s) for -: 'int' and 'str'

In [18]:
idx = ['a','b','c']
print(idx)
# idx2 = idx.copy()
idx2 = [0 for x in idx]
print(idx)
print(idx2)
val = 0.9
val2 = np.round(1-val)
print(val2)

['a', 'b', 'c']
['a', 'b', 'c']
[0, 0, 0]
0.0


In [158]:
class Graph(object):
    """
    Graph object that has sets of nodes and edges
    """

    def __init__(self, edges=set(), nodes=set()):
        self.parents = {}
        self.children = {}
        self.nodes = nodes
        if len(nodes) > 0:
            self.size = len(nodes)
        else:
            self.size = 0
        self.edges = edges

        self.build_parent_and_child_sets()

    def add_node(self, node):
        """
        Add node to graph
        """
        if node not in self.nodes:
            self.size += 1
            self.nodes.add((node))
        else:
            pass

    def build_parent_and_child_sets(self):
        """
        Loop through set of edges and
            - add nodes to Graph object
            - create Graph.parents, Graph.children dictionaries
        """
        for edge in self.edges:
            u, v = edge
            self.add_node(u)
            self.add_node(v)

            if v not in self.parents:
                self.parents.update({v: set(u)})
            else:
                self.parents[v].add(u)

            if u not in self.children:
                self.children.update({u: set(v)})
            else:
                self.children[u].add(v)

    def get_parents(self, node):
        """
        Return parents of node
        """
        if node in self.parents:
            return self.parents[node]
        else:
            return set()

    def get_children(self, node):
        """
        Return children of node
        """
        if node in self.children:
            return self.children[node]
        else:
            return set()

    def is_active(self, a, b, Z):
        """
        Verify if there exists an active trail from node a to b given evidence set Z
        """
        # Find set Y of all nodes that are d_separated from a
        Y = self.d_separated(a, Z)

        # If b is in Y then there is no active trail
        return not (b in Y)

    def d_separated(self, X, Z):
        """
        Find the set Y of all d-separated nodes such that

                d-sep_G(X indep Y | Z) is True

        Uses the Reachable() algorithm 3.1 in PGM book
        """
        # Find all reachable nodes from node X given Z
        R = self.reachable(X, Z)

        # Return nodes in G that are not in R and not in Z
        dsep_nodes = self.nodes - R - Z

        return dsep_nodes

    def reachable(self, X, Z):
        """ 
        Find all nodes that are reachable via an active trail from the given
        node and evidence set.

        Based on Algorithm 3.1, page 75, in PGM book

        inputs:
            X: starting node
            Z: set of observations
        outputs:
            R: set of nodes reachable via active trail
        """
        # Phase 1: insert all ancestors of Z into A
        L = Z.copy()  # set L to be the set of observations
        A = set()  # set A to be the empty set
        while len(L) != 0:
            Y = L.pop()  # remove an item from the set
            if Y not in A:
                L = L.union(self.get_parents(Y))  # Y's parents need to be visited
            A = A.union(Y)  # Y is ancestor of evidence

        # Phase 2: traverse active trails starting from node
        L = {(X, 'up')}
        V = set()  # (node, direction) marked as visited
        R = set()  # Nodes reachable via active trail
        while len(L) != 0:
            # select some (Y, dr) from L
            (Y, dr) = L.pop()
            if (Y, dr) not in V:
                if Y not in Z:
                    R = R | {Y}  # Y is reachable
                V = V | {(Y, dr)}  # mark (Y, dr) as visited
                if dr == 'up' and Y not in Z:
                    # trail up through Y active if Y not in Z
                    for z in self.get_parents(Y):
                        L = L.union({(z, 'up')})  # Y's parents to be visited from bottom
                    for z in self.get_children(Y):
                        L = L.union({(z, 'down')})  # Y's children to be visited from top
                elif dr == 'down':
                    # trails down through Y
                    if Y not in Z:
                        # downward trails to Y's children are active
                        for z in self.get_children(Y):
                            L = L.union({(z, 'down')})  # Y's children to be visited from top
                    if Y in A:
                        # v-structure trails are active
                        for z in self.get_parents(Y):
                            L = L.union({(z, 'up')})  # Y's parents to be visited from bottom
        return R
    
    def Pearl_init(self, x, E):
        """
        Pearl's Message Passing Algorithm for ECEN760 Project
        
        Parameters:
            x : node to query
            E : dict of evidence sets
        
        Returns:
            lmda : lambda(x) 
            pi   : pi(x)
            P    : P(x | e)
        """
        
        # Initialize network
        E = set()
        e = set()
        
        for x in all_x:
            
        
        


def read_file(fname):
    """
    Read problem file, generate graph and questions
    """
    g_list = []  # list of graphs
    q_list = []  # list of queries
    edges = set()
    queries = []
    V, M, Q = 0, 0, 0
    with open(fname) as f:
        for raw_line in f:
            # split the line into components separated by whitespace
            line = raw_line.split()
            # skip '#' as comment
            if line[0][0] == '#':
                continue

            # New Graph description
            elif all([x.isdigit() for x in line]):
                edges = set()
                queries = []
                V, M, Q = [int(x) for x in line]
                # V: number of nodes
                # M: number of edges
                # Q: number of queries

            # Edges
            elif all([x.isalpha() for x in line]) and len(edges) < M:
                u, v = line
                edges = edges | {(u, v)}

            # Queries
            elif line[1] == '|' and len(queries) < Q:
                y = line[0]  # source node Y
                z = {x for x in line[2:]}  # evidence set Z
                queries.append((y, z))

            # Create Graph object
            if (len(edges) == M) and (len(queries) == Q):
                G = Graph(edges=edges)

                # Validate graph
                err = False
                if len(G.nodes) != V:
                    print('Not the correct number of nodes')
                    err = True
                if len(G.edges) != M:
                    print('Not the correct number of edges')
                    err = True
                if err:
                    return

                g_list.append(G)
                q_list.append(queries)

    return g_list, q_list                        

# Build Graph from homework 1, problem 3
nodes = set(('A','B','C','D','E','F','G','H','I','J','K','L','M'))
edges = set([('A','D'),('B','D'),('D','G'),('D','H'),('G','K'),('H','K'),\
             ('H','E'),('C','E'),('E','I'),('F','I'),('F','J'),('I','L'),\
             ('J','M')])
G = Graph(edges=edges)

In [159]:
# part (f)
Z = set(('K','E'))
dsep_nodes = G.d_separated('H', Z)
print('dsep nodes:', dsep_nodes)

$$ A={'K', 'E', 'B', 'A', 'H', 'G', 'D', 'C'}   Y=D   L=set()
hello!!
(Y,dr)=('H', 'up')
&& R=set()   Y=H   Z={'K', 'E'}   L=set()
RRR={'H'}
V={('H', 'up')}   Y=H   L=set()   Z={'K', 'E'}
dr=up
yoyoyo
parents of H -> {'D'}
tmp_iter=set()
children of H -> {'K', 'E'}
**tmp_iter={'K', 'E'}
z=K  L={('K', 'down')}
z=E  L={('K', 'down'), ('E', 'down')}
hello!!
(Y,dr)=('K', 'down')
&& R={'H'}   Y=K   Z={'K', 'E'}   L={('E', 'down')}
V={('K', 'down'), ('H', 'up')}   Y=K   L={('E', 'down')}   Z={'K', 'E'}
dr=down
hello!!
(Y,dr)=('E', 'down')
&& R={'H'}   Y=E   Z={'K', 'E'}   L=set()
V={('K', 'down'), ('E', 'down'), ('H', 'up')}   Y=E   L=set()   Z={'K', 'E'}
dr=down
dsep nodes: {'H'}


In [72]:

# # print('children', G.children)
# # print('parents', G.parents)
# # print('nodes', G.nodes)
# # print('size', G.size)

# start = 'L'
# visited, stack = set(), [start]
# while stack:
#     vertex = stack.pop()
#     if vertex not in visited:
#         visited.add(vertex)
#         stack.extend(G.get_parents(vertex) - visited)
# result = visited-set((start))
# print('end visited {}'.format(result))
# a1 = result
# a2 = G.find_ancestors('L')
# print('a1',a1)
# print('a2',a2)
# print(a1 == a2)

# node = 'I'
# print('find desc of',node)
# print(G.find_descendants(node))

# # find ancestors
# print('find ancestors')
# print(G.find_ancestors('L'))
# print('--find ancestors')



# nodes = set(('A','B','C','D','E','F','G','H','I','J','K','L','M'))
# print(nodes)

dsep nodes: None


In [102]:
A = set()
i = 0
print('hello')
Z = set(('K','E'))
Z.pop()
b = set(('asdf','asdf','qwe','g'))
a=Z.union(b)
print(Z)
print(a)
node = 'L'
L = set([(node, 'up'),('B','down')])
L
('B', 'up') in L

hello
{'E'}
{'qwe', 'asdf', 'g', 'E'}


False

In [41]:
s = set()
s.add('a')
print(s)
s.add('b')
print(s)
s.add('a')
s

l = []
l.append('b')
print(l)
l2 = set(l)
print(l2)
print(isinstance(l2, list))
isinstance(l2, set)

print(l2)
l2.add({})
print(l2)

{'a'}
{'b', 'a'}
['b']
{'b'}
False
{'b'}


TypeError: unhashable type: 'dict'